name: Bump version

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  bump-version:

    runs-on: ubuntu-latest

    if: ${{ github.event.pull_request.merged == true }}

    # determine which part to bump from the PR comment;
    # the comment should contain a string in the format "[bumpversion:<part>]"
    env:
      BUMP_PART: ${{ contains(github.event.pull_request.body, '[bumpversion:major]') && 'major' || (contains(github.event.pull_request.body, '[bumpversion:patch]') && 'patch' || 'minor') }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install bumpversion
        run: |
          python -m pip install --upgrade pip
          pip install bump2version

      # bumpversion wants to make a commit, so we must let git know an identity
      # we use the email and name of the original committer for that
      - name: Set git identity
        run: |
          git config --local user.name "${{ github.event.commits[0].author.name }}"
          git config --local user.email "${{ github.event.commits[0].author.email }}"

      # first retrieve the current version from the _version.py file using sed,
      # then update it
      - name: Run bumpversion
        run: |
          currentver=$(sed -nr 's/__version__\s*=\s*(\S)(.+)\1\s*$/\2/p' ryebot/_version.py)
          bump2version ${{ env.BUMP_PART }} ryebot/_version.py --current-version $currentver --no-configured-files --commit --message "Autobump version: {current_version} → {new_version}" --verbose
          git push origin
